[tools]
chezmoi = "latest"
java = "temurin-21"
node = "20"
go = "latest"
kubectx = "latest"
stern = "latest"
github-cli = "latest"
lua = "5.4"
kubie = "latest"
kubespy = "latest"
kubectl = "1.30"
python = "3.13"
gradle = "8.1.1"
telepresence = "2.20.2"
maven = "4.0.0-rc-2"
